version: "3.7"

services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    #volumes:
      #- ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      #- ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      microservices-network-docker: 
        ipv4_address: "10.10.0.200"
networks:
  microservices-network-docker:
    external:
      name: microservices-network-docker
